import React, { useEffect } from 'react'
import styles from './PrivacyAndSecurity.module.scss' //Error: global CSS cannot be imported from files other than your Custom <App>.
import Link from 'next/link'

function Privacy() {

    useEffect(() => {
        document.querySelector("body").style.backgroundSize = "contain";
        document.querySelector("body").style.backgroundRepeat = "repeat";
        },[])

    return (
        <div className={styles.privacyAndSecurity}>
            <h2>PRIVACY & SECURITY POLICY</h2>
            <div className={styles.content}>
                <h3 className={styles.lastUpdated}>Last Updated: March 2021</h3>
                <p>boomrng, Limited Liability Company and its affiliated companies (collectively “boomrng,” “we,” or “our”) value customers (sometimes referred to herein as “you”) and respect their privacy.  This Privacy Policy (this "Policy") describes boomrng’s collection, processing and use of customer, mobile application user, and website visitor information (collectively, “personal information” or “data”) when you interact with or use boomrng customer service, promotions, mobile applications, social media and websites (collectively, “Applications”). By using our Applications, or by choosing to submit personal information to boomrng, you signify your consent to all of the terms of this Policy. If you do not agree with the terms of this Policy, please do not use the Applications or submit any personal information to boomrng. This Privacy Policy has been compiled to better serve those who are concerned with how their “Personally Identifiable Information” (“PII”) is being used online. PII, as described in US privacy law and with respect to information security, is information that can be used on its own or with other information to identify, contact, or locate a single person, or to identify an individual in context, and is included in the term “personal information” herein. boomrng wants you to be confident that your personal information is being handled securely and give you an opportunity to contact us with privacy-related inquiries and requests. Please read this Policy carefully to get a clear understanding of how we collect, use, protect or otherwise handle your personal information.</p>
                <p>We strive to treat our users the way we want to be treated online. In short, we do the following:</p>
                <p>(1) We collect information to facilitate the basic functionality of, and to improve, our Applications.</p>
                <p>(2) We share information (a) as you direct us; (b) with service providers (such as our hosting and email providers), like many websites you use daily; and (c) to protect our users, artists, and ourselves from general wrongdoing (such as illegal activities).</p>
                <p>Please read on for details about your privacy and how we collect and use information.</p>
                <h3>COLLECTION OF INFORMATION</h3>
                <p>The personal information we collect depends on how you interact with us, the Applications you use, and the choices you make. We collect and process personal information about you with your consent and/or as necessary to provide the products and services you use, operate our business, meet our contractual and legal obligations, protect the security of our systems and our customers, or fulfil other legitimate interests. boomrng obtains the categories of personal information listed above from the following categories of sources:</p>
                <ul>
                    <li>Information you provide directly: We collect personal information you provide to us. For example, we collect your name, email address, postal address, phone number, fax number, demographics, and other information you provide us. If you make a purchase, we also collect credit card numbers and other payment information. If you provide information about anyone other than yourself, you represent and warrant that you have the permission and right to provide the information. If you submit your information in response to a registered user's invitation, your personal information will not be shared with any third parties for marketing purposes. If you register for an Account, your personal information will be used to maintain your Account and Address Book, and we may also send you emails from time to time with information about new features or other news that we think will be of interest to you. If you no longer wish to receive this information from us, you can follow the “unsubscribe” instructions in the messages or you can opt out by contacting us at info@boomrng.us.</li>
                    <li>Information collected automatically: To help us improve our services, we may also collect information to analyze how visitors use our Applications, including the time and date of visits, the referring website, the length of the visit, the web pages viewed during a visit, time spent on a particular web page, the links followed, the type of web browser used, the web site visited before and after our website, and the visitor’s IP address (which is the number assigned to the visitor’s computer to identify its location on the Internet). While we do not use this information to identify visitors individually, we re-serve the right to do so in circumstances where we determine in our reasonable judgment it may be appropriate to comply with legal process or law enforcement or to protect our rights or the rights of any third party.</li>
                </ul>
                <p>Third-Party Sources:  We also obtain information from third parties. We protect information obtained from third parties according to the practices described in this statement, plus any additional restrictions imposed by the source of the information. These third-party sources include:</p>
                <ul>
                    <li>Data brokers from which we purchase demographic data to supplement the data we collect;</li>
                    <li>Applications and services, such as social networks, that make users' information available to others;</li>
                    <li>Service providers that help us determine your device's location based on its IP address to customize certain products to your location;</li>
                    <li>Partners with which we offer co-branded services or engage in joint marketing activities; and</li>
                    <li>Publicly available sources, such as open government databases or other data in the public domain.</li>
                </ul>
                <p>We may combine your personal information collected across the above sources. You may always choose not to provide personal information, but if you so choose, certain products and services may not be available to you.  We use the term "devices" to refer collectively to computers and mobile devices, as well as the internet browsers and other applications on your devices that interact with the internet. boomrng engages in cross device data collection which refers to the process of collecting data from devices that have been determined through statistical analysis to be linked or related. Our partners whom we employ to provide this service use cross device data to provide interest-based advertising services to our customers and to deliver tailored ads to users across multiple devices.</p>
                <h3>USE OF YOUR PERSONAL INFORMATION</h3>
                <p>boomrng uses your personal information collected through our Application for purposes described in this Policy or otherwise disclosed to you. For example, we use your personal information to:</p>
                <ul>
                    <li>provide and deliver services, including securing, troubleshooting, improving, and personalizing those products;</li>
                    <li>operate and improve our Applications and business, including our internal operations and security systems,</li>
                    <li>understand you and your preferences to enhance your experience using our Applications,</li>
                    <li>process your transactions,</li>
                    <li>provide customer service and respond to your questions,</li>
                    <li>perform research and analysis aimed at improving our products, services and technologies,</li>
                    <li>send you information, including confirmations, invoices, technical notices, updates, security alerts, and support and administrative messages,</li>
                    <li>communicate with you about new products, offers, promotions, rewards, contests, upcoming events, and other about our products and those of our selected partners, and</li>
                    <li>display content, including advertising, that is customized to your interests and preferences.</li>
                </ul>
                <p>In carrying out these purposes, we combine data we collect from different sources to give you a more seamless, consistent, and personalized experience.  Please note that for US customers, upon account registration, you will be signed up for our marketing communications. boomrng may contact you from time to time through certain reputable third-party firms for market research purposes, to the extent you have provided your consent for us to do so. Participation in any such activities by you is strictly voluntary and you can always opt-out of these communications, as further detailed below.</p>
                <p>To opt out: Regarding commercial communications you have opted in to receive, you can revoke your consent to receive such commercial communications at any time by clicking on the appropriate link contained in any such email communication. Your opt-out does not apply to communications relating to Application information (including policy updates), legal notices, purchases, customer service/online consumer care matters, or automatically generated non-commercial messages (confirmation emails, order receipts, etc.). To the extent you have provided consent to receive text messages or push notifications, you can opt-out of such messages by following the instructions in the communication, replying back, or visiting the settings on your mobile device.</p>
                <h3>DATA RETENTION</h3>
                <p>Except as provided herein, we may retain your personal information for the longer of (a) the maximum extent allowable by law after we become aware that you have ceased using our Applications or (b) for so long as we have a legitimate business need for the information or to fulfill any legal and regulatory obligations. We may retain other information that is not personally identifiable for backups, archiving, prevention of fraud and abuse, analytics, or where we otherwise reasonably believe that we have a legitimate reason to do so.</p>
                <h3>SHARING OF YOUR PERSONAL INFORMATION</h3>
                <p>Except as disclosed in this privacy policy, boomrng does not share your personal information with any outside parties.  We share personal information with your consent or as necessary to complete your transactions or provide the products or services you have requested or authorized. We may also share your personal information within our corporate group, including with our subsidiaries, affiliates, and divisions, all of whom may use your data for the purposes disclosed herein. In addition, we may share your personal information with our approved and appointed distributor network.</p>
                <p>We may share your personal information with service providers who perform services on our behalf. For example, we may hire other companies to handle the processing of payments, to provide data storage, to host websites, to fulfill orders and shipments, to assist in direct marketing, analyze your interests and preferences and to conduct audits, etc. Those companies will be permitted to obtain only the personal information they need to provide the service. They are required to maintain the confidentiality of the information and are prohibited from using it for any other purpose. boomrng maintains contracts with these third parties requiring their treatment (access, use and disclosure) of personal information to be consistent with our obligations under the law.</p>
                <p>Information about our customers, including personal information, may be disclosed as part of any merger, transfer, divestiture, acquisition, or sale of all or a portion of the company and/or its assets, as well as in the unlikely event of insolvency, bankruptcy, or receivership, in which personal information would be transferred as one of the business assets of the company. We will notify you of such an occurrence as described in the "Changes to This Privacy Policy" section below.</p>
                <p>We reserve the right to disclose your personal information if we have a good faith understanding we are required to do so by law (including to meet national security or law enforcement requirements), or in the good-faith belief that such action is reasonably necessary to comply with legal process, respond to claims, or protect the rights, property or safety of our company, employees, customers, or the public.</p>
                <p>The Applications may contain links to other third-party websites, or feature tools and services that are operated by third parties, as described above. These other websites and providers may have their own privacy policies and terms and conditions that are not governed by this Policy. We are not responsible for the privacy practices or the content of any website(s) owned and operated by any such third parties. Other websites may collect and treat information collected differently, so we encourage you to carefully read and review the privacy policy for each website you visit. Any links from the Applications to other websites, or references to products, services or publications other than those of boomrng, do not imply the endorsement or approval of such websites, products, services or publications by boomrng.</p>
                <h3>SOCIAL MEDIA</h3>
                <p>When you use the Applications, please note that we may share your hashed email addresses, as well as other pseudonymous identifiers and data about your use of the Applications and your device if applicable, with Facebook and other social media networks, as well as other online platforms and related reputable service providers, in order to utilize services which may include but are not limited to Facebook’s Custom Audience and pixel services. You can learn more about how to opt out of having such activity sent to Facebook at <a href="https://www.facebook.com/help/2207256696182627" target="_blank">https://www.facebook.com/help/2207256696182627</a> and <a href="https://www.facebook.com/off_facebook_activity/">https://www.facebook.com/off_facebook_activity/</a>.</p>
                <p>Otherwise, only after you have actively clicked the applicable link yourself, your internet browser will establish a connection to the servers of the relevant social network; therefore, by clicking the appropriate button (e.g., “Like”), you give your consent to your internet browser establishing a connection to the servers of the relevant social network and transmitting data relating to the use of the website to the relevant social network provider. We may combine information we receive from those platforms with other information we collect from you or other sources and use and disclose it as described in this privacy policy.</p>
                <p>Once engaged with the relevant social media website, your use and browsing will be governed by the data protection statements/privacy policies of the relevant providers.  Except where required by applicable law or regulation, we do not control and do not assume any responsibility for the use of personal information by such third parties. For more information about the third party's purpose and scope of their use of personal information in connection with sharing features, please visit the privacy policies of these third parties.</p>
                <h3>FAIR INFORMATION PRACTICES AND YOUR RIGHTS</h3>
                <p>The Fair Information Practice Principles form the backbone of privacy law in the United States and the concepts they include have played a significant role in the development of data protection laws around the globe.  Understanding the Fair Information Practice Principles and how they should be implemented is critical to comply with the various privacy laws that protect personal information. In order to comply with Fair Information Practices, we will notify you of a data breach via email within seven (7) business days. We also agree to the Individual Redress Principle which requires that individuals have the right to legally pursue enforceable rights against data collectors and processors who fail to adhere to the law. This principle requires not only that individuals have enforceable rights against data users, but also that individuals have recourse to courts or government agencies to investigate and/or prosecute non-compliance by data processors.</p>
                <p>Your principal rights under data protection law are:</p>
                <ul>
                    <li>the right to access;</li>
                    <li>the right to rectification;</li>
                    <li>the right to erasure;</li>
                    <li>the right to restrict processing;</li>
                    <li>the right to object to processing;</li>
                    <li>the right to data portability;</li>
                    <li>the right to complain to a supervisory authority; and</li>
                    <li>the right to withdraw consent.</li>
                </ul>
                <p>You have the right to confirmation as to whether we process your personal information and, where and how we access your personal information, together with certain additional information. That additional information includes details of the purposes of the processing, the categories of personal information concerned and the recipients of the personal information. Providing the rights and freedoms of others are not affected, we will supply to you a copy of your personal information upon request. The first copy will be provided free of charge, but additional copies may be subject to a reasonable fee. You can access your personal information by using the Applications when logged in or by contacting us.</p>
                <p>You have the right to have any inaccurate personal information about you rectified and, taking into account the purposes of the processing, to have any incomplete personal information about you completed. In some circumstances you have the right to the erasure of your personal information without undue delay. Those circumstances include: the personal information is no longer necessary in relation to the purposes for which it was collected or otherwise processed; you withdraw consent to consent-based processing; you object to the processing under certain rules of applicable data protection law; the processing is for direct marketing purposes; and the personal information has been unlawfully processed. However, there are exclusions of the right to erasure. The general exclusions include where processing is necessary: for exercising the right of freedom of expression and information; for compliance with a legal obligation; or for the establishment, exercise or defense of legal claims.</p>
                <p>In some circumstances you have the right to restrict the processing of your personal information. Those circumstances include the following: you contest the accuracy of the personal information; processing is unlawful but you oppose erasure; we no longer need the personal information for the purposes of our processing, but you require personal information for the establishment, exercise or defense of legal claims; and if you have objected to processing, pending the verification of that objection. Where processing has been restricted on this basis, we may continue to store your personal information. However, we will only otherwise process it: with your consent; for the establishment, exercise or defense of legal claims; for the protection of the rights of another natural or legal person; or for reasons of important public interest.</p>
                <p>You have the right to object to our processing of your personal information on grounds relating to your particular situation, but only to the extent that the legal basis for the processing is that the processing is necessary for: the performance of a task carried out in the public interest or in the exercise of any official authority vested in us; or the purposes of the legitimate interests pursued by us or by a third party. If you make such an objection, we will cease to process the personal information unless we can demonstrate compelling legitimate grounds for the processing which override your interests, rights and freedoms, or the processing is for the establishment, exercise or defense of legal claims.</p>
                <p>You have the right to object to our processing of your personal information for direct marketing purposes (including profiling for direct marketing purposes). If you make such an objection, we will cease to process your personal information for this purpose.</p>
                <p>You have the right to object to our processing of your personal information for scientific or historical research purposes or statistical purposes on grounds relating to your particular situation, unless the processing is necessary for the performance of a task carried out for reasons of public interest.</p>
                <p>To the extent that the legal basis for our processing of your personal information is your consent or that the processing is necessary for the performance of a contract to which you are party or in order to take steps at your request prior to entering into a contract, and such processing is carried out by automated means, you have the right to receive your personal information from us in a structured, commonly used and machine-readable format. However, this right does not apply where it would adversely affect the rights and freedoms of others.</p>
                <p>If you believe that our processing of your personal information infringes data protection laws, you have a legal right to lodge a complaint with a supervisory authority responsible for data protection. You may do so in the EU member state of your habitual residence, your place of work or the place of the alleged infringement.</p>
                <p>To the extent that the legal basis for our processing of your personal information is your consent, you have the right to withdraw that consent at any time. Withdrawal will not affect the lawfulness of processing before the withdrawal.</p>
                <p>For your protection, we may require proof and verification of identity and jurisdiction of residency before we can answer the above requests. If you wish to make such a request, you may contact us at the applicable mobile application support email indicated herein or in the Application. If we change or delete your personal information or if you decline to actively share certain personal information with us, we may not be able to provide you with our services or some of the features and functionality of our Applications. Once we have verified that you own the account, we will honor such requests at our discretion and in accordance with applicable law.</p>
                <p>Device permissions:  Mobile platforms have permission systems for specific types of device data and notifications, such as camera and microphone as well as push notifications. Where applicable, you can change your settings on your device to either consent or oppose the collection of the corresponding information or the display of the corresponding notifications. Depending on the manner in which you make changes to your settings, certain services may lose partial or full functionality.</p>
                <p>Uninstall:  You can stop all information collection by Applications by disabling call forwarding and deactivating your account by following the instructions on the Application’s settings screen and then uninstalling the Applications using the standard uninstall process for your device. If you uninstall the Applications from your mobile device, the unique identifier associated with your device will continue to be stored. If you reinstall the Applications on the same mobile device, we will be able to re-associate this identifier to your previous transactions and activities.</p>
                <p>Email:  You may choose to stop receiving our newsletter or marketing emails by following the unsubscribe instructions included in these emails or you can contact us at info@boomrng.us Opting out of newsletters and marketing emails will not affect communication via email or telephone relating to your orders.</p>
                <p>Notwithstanding any of the foregoing, when we enable you to create a profile, and share information such as messages, photos, and videos with others, we cannot control the actions of others with whom you may choose to share your pages and information.</p>
                <p>Nevada Users:  Nevada residents have the right to opt out of the sale of certain “covered information” collected by operators of websites or online services.</p>
                <p>Additional rights for residents of the European Economic Area (EEA) and the State of California are further set forth below.</p>
                <h3>COOKIES</h3>
                <p>We collect the information we mentioned in the previous paragraphs through the use of various technologies, including cookies. A cookie is a piece of data that a web site or web-based application can send to your browser, which is then stored on your computer as an anonymous tag that identifies your computer, and in some cases, you.  Some boomrng pages use cookies, sent by boomrng, its third-party vendors, or other technologies to better serve you when you access and use the Applications. You can set your browser to notify you before you receive a cookie, giving you the chance to decide whether to accept it. You also can set your browser to turn off cookies. If you do so, however, some websites, including ours, may not work properly. Our cookies are linked to personal information; however, our third-party vendor cookies only collect data in the aggregate.</p>
                <p>We receive data from the various devices you use to access our Applications and services. This may include location and IP information, device ID information, the pages within our site that you visit, or the type of browser you are using. We may even receive GPS information from your device so we can provide you location-based services.  We may pool the information obtained from cookies with other anonymous information for the purposes of sending direct mail. If you wish to not receive direct mail, you may contact us via the methods described at the end of this Policy.  In addition to cookies, such other technologies may include: "pixel tags" (also known as a "clear GIFs" or "web beacons") which are tiny images (in most cases, typically just one-pixel) that can be placed on a web page or in our electronic communications to you in order to help us measure the effectiveness of our content by, for example,</p>
                <p>counting the number of individuals who visit us online or verifying whether you’ve opened one of our emails or seen one of our web pages; and "HTML5" (the language some websites, such as mobile websites are coded in) may be used to store information on your computer or device about your website usage activities and to help determine how our Applications are being used by our visitors, how the services can be improved and to customize our Applications and services for our users.</p>
                <p>Web browsers may offer users of our services the ability to disable receiving certain types of cookies; however, if cookies are disabled, some features or functionality of our Applications may not function correctly. The “help” menu on most internet browsers contains information on how to disable cookies, or you can visit www.aboutcookies.org/how-to-control-cookies/. The above tracking technologies may be deployed by us or our service providers on our behalf.  Most browsers allow you to refuse to accept cookies and to delete cookies. The methods for doing so vary from browser to browser, and from version to version. You can however obtain up-to-date information about blocking and deleting cookies via these links: <a href="https://support.google.com/chrome/answer/95647?hl=en" target="_blank">https://support.google.com/chrome/answer/95647?hl=en</a> (Chrome); <a href="https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences" target="_blank">https://support.mozilla.org/en-US/kb/enable-and-disable-cookies-website-preferences</a> (Firefox); <a href="http://www.opera.com/help/tutorials/security/cookies/" target="_blank">http://www.opera.com/help/tutorials/security/cookies/</a> (Opera); <a href="https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies" target="_blank">https://support.microsoft.com/en-gb/help/17442/windows-internet-explorer-delete-manage-cookies</a> (Internet Explorer); <a href="https://support.apple.com/kb/PH21411" target="_blank">https://support.apple.com/kb/PH21411</a> (Safari); and <a href="https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy" target="_blank">https://privacy.microsoft.com/en-us/windows-10-microsoft-edge-and-privacy</a> (Edge). Blocking all cookies will have a negative impact upon the usability of many websites. If you block cookies, you will not be able to use all the features on our website.</p>
                <h3>DO NOT TRACK DISCLOSURES</h3>
                <p>Do Not Track (“DNT”) is a privacy preference that users can set in certain web browsers. DNT is a way for users to inform websites and services that they do not want certain information about their webpage visits collected over time and across websites or online services. Please note that we do not respond to or honor DNT signals or similar mechanisms transmitted by web browsers.</p>
                <h3>EUROPEAN DATA PROTECTION RIGHTS</h3>
                <p>If the processing of personal information about you is subject to European Union data protection law, you have certain rights with respect to that data:</p>
                <ul>
                    <li>You can request access to, and rectification or erasure of, personal information;</li>
                    <li>If any automated processing of personal information is based on your consent or a contract with you, you have a right to transfer or receive a copy of your personal information in a usable and portable format;</li>
                    <li>If the processing of personal information is based on your consent, you can withdraw consent at any time for future processing;</li>
                    <li>You can to object to, or obtain a restriction of, the processing of personal information under certain circumstances; and</li>
                    <li>For residents of France, you can send us specific instructions regarding the use of your data after your death.</li>
                </ul>
                <p>To make such requests, contact us at privacy@boomrng.us. When we are processing data on behalf of another party that is the "data controller," you should direct your request to that party. You also have the right to lodge a complaint with a supervisory authority, but we encourage you to first contact us with any questions or concerns. Please be aware that those rights set out above may not apply in some instances, for example where our right to processing your personal information may be necessary for exercising the right of freedom of expression (e.g., news gathering), to fulfill contracts with our business partners, or for the establishment, exercise or defense of legal claims.</p>
                <p>We may transfer your personal information to countries other than the country in which the data was originally collected for the purposes described in this Privacy Policy. For example, if you are located outside of the United States, we may transfer your personal information to the United States, where boomrng is headquartered. The countries to which we transfer personal information may not have the same data protection laws as the country in which you initially provided the information. When we transfer personal information across borders, we consider a variety of requirements that may apply to such transfers. Specifically, we may transfer personal information from the European Economic Area to: (a) countries that the European Commissions has deemed to adequately safeguard personal information; (b) pursuant to the recipient’s compliance with standard contractual clauses (also known as Model Clauses), EU-US Privacy Shield, or Binding Corporate Rules; (c) pursuant to the consent of the individual to whom the personal information pertains; or (d) as otherwise permitted by applicable EEA requirements.</p>
                <h3>CALIFORNIA PRIVACY RIGHTS</h3>
                <p>If you are a California resident, the California Consumer Privacy Act (“CCPA”) may provide you with notice and other rights regarding our use of your personal information that are in addition to those set forth elsewhere in this Privacy Policy. The CCPA Notice applies to “Consumers” as defined by the law. Consumers from California have the right to: request information about the categories and sources of personal information collected, and the associated purposes for collection and third-party disclosures; request a copy of their personal information; request deletion of their personal information; and opt out of the sale of personal information. This section describes your CCPA rights as a California Consumer and explains how to exercise those rights. See the above Sections to learn what information we collect from you and how it is collected, used, and shared.</p>
                <p>Access to Information and Data Portability Rights:<br/>
                You have the right to send us a request, no more than twice in a twelve (12) month period, for any of the following for the period that is twelve (12) months prior to the request date: the categories of personal information we have collected about you; the categories of sources from which we collected your personal information; the business or commercial purposes for our collecting or selling your personal information; the categories of third parties to whom we have shared your personal information; the specific pieces of personal information we have collected about you; a list of the categories of personal information disclosed for a business purpose in the prior 12 months, or that no disclosure occurred; and a list of the categories of personal information sold about you in the prior 12 months, or that no sale occurred.</p>
                <p>If we sold your personal information, we will explain: (a) the categories of your personal information we have sold; and (b) the categories of third parties to which we sold personal information, by categories of personal information sold for each third party. You have the right to make or obtain a transportable copy, no more than twice in a twelve-month period, of your personal information that we have collected in the period that is 12 months prior to the request date and are maintaining.</p>
                <p>Data Deletion Rights:<br/>
                Except to the extent we have a basis for retention under CCPA, you may request that we delete your personal information that we have collected directly from you and are maintaining. Note also that we are not required to delete your personal information that we did not collect directly from you. </p>
                <p>Exercising Your Rights:<br/> 
                To make a request for access, portability, or deletion according to your rights under CCPA, residents of California may contact us at privacy@boomrng.us. California Consumers may exercise these rights via an authorized agent who meets the agency requirements of the CCPA. We cannot respond to your request or provide you with personal information if we cannot verify your identity or authority to make the request and confirm that the personal information relates to you. Any request you submit to us is subject to an identification and residency verification process (“Verifiable Consumer Request”). The Verifiable Consumer Request must: (a) provide sufficient information that allows us to reasonably verify you are the person about whom we collected personal information or an authorized representative; and (b) describe your request with sufficient detail that allows us to properly understand, evaluate, and respond to it. Some personal information we maintain about Consumers is not sufficiently associated with enough personal information about the Consumer for us to be able to verify that it is a particular Consumer’s personal information (e.g., clickstream data tied only to a pseudonymous browser ID). As required by the CCPA, we do not include that personal information in response to Verifiable Consumer Requests. If we cannot comply with a request, we will explain the reasons in our response. We will make commercially reasonable efforts to identify Consumer personal information that we collect, process, store, disclose, and otherwise use and to respond to your California Consumer privacy rights requests. We will typically not charge a fee to fully respond to your requests, but we may charge a reasonable fee, or refuse to act upon a request, if your request is excessive, repetitive, unfounded, or overly burdensome.</p>
                <p>We will not discriminate against you in a manner prohibited by the CCPA because you exercise your CCPA rights. However, we may charge a different price or rate, or offer a different level or quality of good or service, to the extent that doing so is reasonably related to the value of the applicable data. In addition, we may offer you financial incentives for the collection, sale and retention and use of your personal information as permitted by the CCPA that can, without limitation, result in reasonably different prices, rates, or quality levels. The material aspects of any financial incentive will be explained and described in its program terms.</p>
                <p>California's "Shine the Light" law, Civil Code section 1798.83, requires certain businesses to respond to requests from California customers asking about the businesses' practices related to disclosing personal information to third parties for the third parties' direct marketing purposes. You may make such a request by contacting us at privacy@boomrng.us. We do not make any representations concerning third parties that do not collect personal information directly through our Applications. To find out more about our “do not track” practices under Cal. Bus. & Prof. Code § 22575, see the “Do Not Track Disclosures” Section of this Privacy Policy. For additional information on your privacy choices and rights, see the “Fair Information Practice and Your rights” Section of this Privacy Policy.</p>
                <h3>SECURITY OF YOUR PERSONAL INFORMATION</h3>
                <p>The security of your personal information is important to us. We take appropriate and reasonable steps designed to help protect your personal information from unauthorized access, use, disclosure, alteration, and destruction. For instance, in some cases we encrypt that information in transit using secure socket layer (SSL) technology. No method of transmission over the internet, or method of electronic storage, is 100% secure. Therefore, while we strive to protect your personal information, we cannot guarantee its absolute security.  If a password is used to protect your account and personal information, it is your responsibility to keep your password confidential.</p>
                <h3>CHILDREN UNDER AGE 18</h3>
                <p>Our Applications are designed for use solely by individuals 18 years and older. By using our Applications, you represent to us that you are at least 18 years old. If you are not at least 18 years old, you may not use our Applications. You may not use our Site to request information from anyone under the age of 18 and we do not knowingly collect personally identifiable information from children under the age of 18. If we learn that any personally identifiable information has been collected from a child under the age of 18 without verification of parental consent, we will delete that information. If you are a parent or legal guardian and you believe that your child under age 18 may have provided personally identifiable information through our Applications, please contact us at info@boomrng.us.</p>
                <h3>CHANGES TO THIS PRIVACY POLICY</h3>
                <p>We reserve the right to change the terms of this Policy at any time when necessary to reflect changes in our products, how we process personal information, or applicable law. When we make changes, we will revise the "last updated" date at the top of the Policy. If there are material changes to this statement, we will provide notice or obtain consent regarding such changes as may be required by law. We encourage you to review this Policy whenever you visit or use one of our Applications.</p>
                <h3>DISPUTE RESOLUTION</h3>
                <p>We are committed to working with you to obtain a fair resolution of any complaint. We encourage you to begin by contacting us. We endeavor to respond to requests promptly. Any dispute arising under or relating to the provisions of this Privacy Policy will be governed in accordance with boomrng’s Terms and Conditions found on our website.  E.U. residents also have the right to lodge complaints with the data protection authority of their country of residence.</p>
                <h3>QUESTIONS</h3>
                <p>For any questions or comments you may have about these Terms, please contact us at: <span><Link href='mailto:info@boomrng.us'>info@boomrng.us</Link></span></p>
            </div>
        </div>
    )
}

export default Privacy
