import React, { useEffect } from 'react'
// import { useHistory } from 'react-router';
import './TermsAndConditions.module.scss'

function Terms() {

    // const history = useHistory();

    useEffect(() => {
    document.querySelector("body").style.backgroundSize = "contain";
    document.querySelector("body").style.backgroundRepeat = "repeat";
    },[])

    return (
        <div className="termsOfService">
            <h2>TERMS & CONDITIONS POLICY</h2>
            <div className="content">
                <h3 className="last-updated">Last Updated: March 2021</h3>
                <p>PLEASE READ THESE TERMS AND CONDITIONS (THESE “TERMS”) CAREFULLY. BY ACCESSING OR USING ANY BOOMRNG, LIMITED LIABILITY COMPANY (“BOOMRNG,” “WE,” “US,” OR “OUR”) WEBSITE OR MOBILE APPLICATION (OR ANY CONTENT, PRODUCT, SERVICE, OR FEATURE AVAILABLE THROUGH THE WEBSITE OR MOBILE APPLICATION, INCLUDING THE EMBEDDED VIEWER) (COLLECTIVELY, THE "APPLICATIONS"), YOU AGREE TO ABIDE BY AND BE BOUND BY THE TERMS DESCRIBED HEREIN AND BY ALL TERMS, POLICIES AND GUIDELINES INCORPORATED BY REFERENCE, AS WELL AS ANY ADDITIONAL TERMS AND RESTRICTIONS PRESENTED IN RELATION TO SPECIFIC CONTENT OR A SPECIFIC PRODUCT, SERVICE OR FEATURE. IF YOU DO NOT AGREE TO ALL OF THESE TERMS, DO NOT USE THE APPLICATIONS. WE MAY MODIFY THESE TERMS (INCLUDING THE PRIVACY POLICY) FROM TIME TO TIME BY DISPLAYING UPDATED TERMS ON THE APPLICATIONS. YOUR CONTINUED USE OF THE APPLICATIONS AFTER UPDATED TERMS ARE DISPLAYED INDICATES YOUR AGREEMENT TO THE MODIFIED TERMS.</p>
                <p>These Terms are not intended to alter the terms or conditions of any content license agreement you may have with boomrng, its subsidiaries or affiliates, and to the extent of any conflict, the terms of your content license agreement will prevail. By using the Applications, you represent and warrant that you are over the age of 18 and are lawfully able to accept these Terms. If you are using the Applications on behalf of any entity, you further represent and warrant that you are authorized to accept these Terms on such entity's behalf, and that such entity agrees to indemnify boomrng for violations of these Terms.</p>
                <p>NOTICE TO PARENTS AND/OR GUARDIANS: You are responsible for monitoring and supervising your child's use of the Applications. If your child is using the Applications without your express consent and is under 18, please contact us immediately so that we can disable his or her access.</p>
                <h3>PRIVACY POLICY</h3>
                <p>boomrng is committed to protecting your privacy. Please refer to our Privacy Policy found <span className="link" onClick={()=> history.push('/privacy-and-security')}>here</span> for information on how we collect, use and disclose personal information.</p>
                <h3>OWNERSHIP OF THE APPLICATIONS AND ITS CONTENTS</h3>
                <p>The Applications are owned by boomrng. Unless otherwise noted, all rights, title and interest in all information including, but not limited to, screens, texts, usernames, passwords, web pages, or other materials (collectively “Information”) appearing in and on the Applications are the exclusive property of boomrng. boomrng’s use of such information is subject to its Privacy Policy.  You acknowledge that all content on or provided through the Applications, including, but not limited to software, images, illustrations, whether tangible or intangible (collectively “boomrng Content”), is protected by copyrights, trademarks or service marks and other intellectual property rights which are owned and controlled by boomrng or by third parties that have licensed their content or the right to market and sell their products to boomrng. Such content may not be copied, reproduced, republished, uploaded, posted, transmitted, distributed or exploited in any way, without proper permission from the content’s owner.  "boomrng" and other names, trademarks, service marks, and indicia of source ("boomrng Trademarks") are owned by boomrng. You may not use the boomrng Trademarks in connection with any products or services that do not belong to boomrng or in any manner likely to cause confusion about the source of any product or service, that implies that boomrng endorses anyone else’s product or service, or that disparages or discredits boomrng.</p>
                <h3>YOUR ACCOUNT</h3>
                <p>To create an online address book ("Address Book"), you must register by creating a user account ("Account") with a username and password and providing other information as part of the registration process. When you register and create an Account, you can add contact information to your Address Book. You may also send emails inviting others to be added to your Address Book by providing you with their contact and other information. If the person you invite wishes to be included in your Address Book, he or she may visit our Applications to complete an online form, which includes both mandatory information (such as name and address) and optional information (such as cell phone, home phone, preferred email, birth month and day, and name of spouse, if applicable). A person does not have to register and create an account to be included in your Address Book. A registered user may respond to an invite request and be added to another registered user’s Address Book without manually entering their contact information. If you register for an Account and create an Address Book, you agree to update or delete any entries in your Address Book as requested by the person(s) who provided the information or by the person(s) about whom the information applies (e.g., a spouse). If a person notifies us that he or she wishes to have his or her contact information deleted from your Address Book, we will notify you about the request; we reserve the right to delete the person’s contact information from your Address Book.</p>
                <p>You are responsible for (1) maintaining the confidentiality of your username and password and for notifying us immediately if you become aware of any actual or suspected unauthorized use, (2) all uses of your username or password, (3) all activity, including purchases, conducted under your Account (e.g., if others send a link on your behalf inviting a person to be added to your Address Book), and (4) providing accurate information in connection with your Account. You may terminate your Account at any time by contacting info@boomrng.us and we will delete your account as soon as possible. If you decide to terminate your Account, we will delete your Address Book, so be sure to export or print any contact information in your Address Book that you wish to retain before you terminate your Account. We reserve the right to retain a copy of your Address Book for a limited period if we determine in good faith that it may be appropriate to do so to comply with legal process, law enforcement, or law, to protect our property or rights or the rights or safety of any third party, to address suspected illegal activity, and for similar reasons we determine in good faith are appropriate.</p>
                <p>You may not use someone else’s name, or post, upload or submit any content that violates any third-party rights, is against the law, or that is offensive, obscene or otherwise objectionable (in boomrng’s sole discretion). We may, in our sole discretion, suspend, disable, or delete your Account (or any part thereof) or block or remove any content that you submit, for any lawful reason, including if we determine that you have violated these Terms or that your conduct or content may damage our reputation or goodwill.  You are responsible for all activity that occurs under your Account, including any activity by unauthorized users. You may not allow others to use your Account or share your Account with others except as otherwise provided herein. You agree to notify us immediately if you suspect any unauthorized use of your Account, access to your password, or any other breach of security. In the event your Account is for any reason shared with or used by anyone other than you, you shall be responsible for informing any such user of these Terms and ensuring compliance with the same. You are solely responsible for any and all use of your Account and although we will not be liable for your losses caused by any unauthorized use of your Account or use by anyone other than you, you may be liable for the losses of boomrng or others due to such uses.  You agree that boomrng, in its sole discretion, may terminate or suspend your use of the Application at any time and for any or no reason in its sole discretion, even if access and use continue to be allowed to others.  Upon such suspension or termination, you must immediately discontinue use of the Applications.  Accessing the Applications after such termination, suspension or discontinuation shall constitute an act of trespass.  Further, you agree that we shall not be liable to you or any third party for any termination or suspension of your access to the Applications. We may block your email address and Internet protocol address to prevent further registration and/or submission of information and content. We are not required to disclose, and may be prohibited by law from disclosing, the reason for the termination or suspension of your Account. After your Account is terminated for any reason, all terms of these Terms survive such termination, and continue in full force and effect, except for any terms that by their nature expire or are fully satisfied. Upon termination, all licenses granted by boomrng will terminate. In the event of Account deletion for any reason, information and content that you submitted may no longer be available. We shall not be responsible for the loss of such information or content.</p>
                <h3>CONDUCT</h3>
                <p>boomrng offers you the ability to submit or post User Content through certain of its Applications, including through social features available within certain of our mobile applications, provided such submission or transmission of User Content is in strict compliance with these terms. For the purposes of these Terms, “User Content” means video, images, text, comments, app store reviews (including the public-facing username as it appears with the review), audio recordings and other content, that you upload, post or transmit (collectively “submit”) to the Applications or any boomrng social media page, or by providing an app review through a third-party service. You expressly agree that you will not use the Applications or send any email containing a boomrng.us link:</p>
                <ol type="a">
                    <li>for any unlawful purpose, including posting, storing, sending, or otherwise transmitting information, data or material that is libelous, obscene, threatening, harassing, or defamatory or which infringes the intellectual property rights of any person or which in any way encourages conduct that would be unlawful or inappropriate;</li>
                    <li>in connection with any unsolicited bulk or commercial messages (commonly known as "spam"), any advertising or other form of communication that violates these Terms or any law or regulation, or in any manner that would disrupt in any way any internet site or services;</li>
                    <li>to initiate or perpetuate any illegal scheme (such as a pyramid scheme);</li>
                    <li>to harvest (or engage in any type of systematic retrieval of) e-mail addresses or other identifiers or information or collect email addresses;</li>
                    <li>to impersonate any person or entity, falsify any sender address, forge anyone’s identity or perform any other fraudulent activity (such as "phishing");</li>
                    <li>to interfere with, or attempt to interfere with, any person’s ability to use the services offered on the Applications;</li>
                    <li>to transmit or otherwise make available through our Applications any computer code, file, program or other element (including any virus, worm, or other harmful malware of any nature) that would interrupt, destroy, interfere with or otherwise cause any other effect that might reasonably be considered undesirable;</li>
                    <li>to register or attempt to use the services under the name of another person, allow another person to use your username or password or your Account, use another person’s Account; or</li>
                    <li>to attempt to (or actually) circumvent the Applications’ security or any means to control access to the Applications’ services.</li>
                </ol>
                <p>We do not, and cannot, pre-screen or monitor all User Content. However, boomrng has the right (but not the obligation) to monitor your conduct and User Content submission on our Applications and you hereby provide your irrevocable consent to such monitoring. You acknowledge and agree that you have no expectation of privacy concerning your submission of any User Content. We have the right, but not the obligation, in our sole discretion to edit, refuse to post, remove, disallow, block or delete any User Content. Under no circumstances will we be liable for any of your User Content.  You shall be solely responsible for any User Content submitted through your Account. We may access, preserve or disclose any of your information or User Content (including without limitation chat text) if we are required to do so by law, or if we believe in good faith that it is reasonably necessary to (i) respond to claims asserted against us or to comply with legal process (for example, subpoenas or warrants), including those issued by courts having jurisdiction over us or you; (ii) enforce or administer our agreements with users, such as these Terms; (iii) for fraud prevention, risk assessment, investigation, customer support, providing the app services or engineering support; (iv) protect the rights, property or safety of boomrng, its users, or members of the public or (v) to report a crime or other offensive behavior. We may also act to remove Objectionable Content. The decision to remove Objectionable Content shall be made in our sole discretion. "Objectionable Content" includes, but is not limited to: (1) User Content that is unlawful, harmful, threatening, abusive, harassing, tortuous, defamatory, or libelous; (2) User Content that is hateful, or advocates hate crimes, harm or violence against a person or group; (3) User Content that may harm minors in any way; (4) User Content that has the goal or effect of "stalking" or otherwise harassing another; (5) Private information about any individual such as phone numbers, addresses, Social Security numbers or any other information that is invasive of another's privacy; (6) User Content that is vulgar, offensive, obscene or pornographic; (7) Unsolicited or unauthorized advertising, promotional materials, "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation; or (8) Material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment.</p>
                <p>We may provide opportunities for you to submit User Content through social features on the Applications or through any other means which are intended to foster and constitute one or more community-based venues for boomrng users to chat, interact, motivate and support one another. As between you and boomrng, you own all User Content that you submit to the Applications, whether directly via the Applications or indirectly (for example, via Facebook or Twitter). However, it is important that you understand that by posting User Content to boomrng Applications or to our social media pages or by providing an app review through a third party service, you are granting boomrng and its affiliates a worldwide, perpetual, irrevocable, nonexclusive, sub-licensable (through multiple tiers) royalty-free license and right to use, copy, transmit, distribute, publicly perform and display (through all media now known or hereafter created), and make derivative works from your User Content (including without limitation, your name and likeness, photographs, testimonials and app reviews) for any purpose whatsoever commercial or otherwise without compensation to you. In addition, you waive any so-called "moral rights" or "performance rights" in your User Content. If you prefer that we do not use your app reviews for promotional purposes, please contact info@boomrng.us. You further grant all users of the Applications permission to view your User Content for their personal, non-commercial purposes. If you make suggestions concerning improving or adding new features to the Applications, we shall have the right to use your suggestions without any compensation to you. For each piece of User Content that you submit, you represent and warrant that: (i) you have the right to submit the User Content and grant the licenses set forth above; (ii) we will not need to obtain licenses from any third party or pay royalties to any third party; (iii) the User Content does not infringe any third party's rights, including intellectual property rights and privacy rights; and (iv) the User Content complies with these Terms and all applicable laws.</p>
                <h3>LICENSE</h3>
                <p>Subject to your compliance with these Terms and solely for so long as you are permitted by us to access and use the Applications, boomrng grants you a limited, non-transferable, non-exclusive, revocable right and license to access and use the Applications for your own personal, non-commercial purposes, a right which may not be assigned or sublicensed to anyone. Any other use is strictly prohibited. You may not use the Applications in connection with any commercial endeavors, such as (i) advertising or soliciting any user to buy or sell any products or services; or (ii) for commercial purposes. Users of the Applications may not use any information obtained from the Applications to contact, advertise to, solicit, or sell to any other user without his or her prior explicit consent. Organizations, companies, and/or businesses may not use the Applications for any purpose unless expressly authorized by boomrng. We may, in our sole discretion, refuse to offer the Applications, or our products or services, to any person or entity, or change the eligibility criteria at any time.  This license will remain in effect unless you violate these Terms, or this license is terminated by you or boomrng.  You agree not to copy, reproduce, redistribute, sell, transfer, create derivative works from, modify, decompile, reverse engineer, or disassemble any Application, product, or service.  If we terminate your Account because you have breached the Terms, you may not be entitled to a refund, unless otherwise required by law. We reserve the right to discontinue any aspect of the Applications at any time. We may investigate and take any available legal action in response to illegal and/or unauthorized uses of the Applications.</p>
                <h3>ALLEGED COPYRIGHT INFRINGEMENT</h3>
                <p>In accordance with the Digital Millennium Copyright Act ("DMCA") and other applicable laws, boomrng has adopted a policy of terminating, in appropriate circumstances and at boomrng's sole discretion, account holders who infringe the intellectual property rights of boomrng or any third party.  If you believe that your intellectual property rights have been violated by boomrng or by a third party, please provide the following information to the boomrng-designated copyright agent listed below.</p>
                <ol type="a">
                    <li>A description of the copyrighted work or other intellectual property that you claim has been infringed;</li>
                    <li>A description of where the material that you claim is infringing is located on the Applications;</li>
                    <li>An address, a telephone number, and an e-mail address where boomrng can contact you;</li>
                    <li>A statement that you have a good-faith belief that the use is not authorized by the copyright or other intellectual property rights owner, by its agent, or by law;</li>
                    <li>A statement by you under penalty of perjury that the information in your notice is accurate and that you are the copyright or intellectual property owner or are authorized to act on the owner’s behalf;</li>
                    <li>Your electronic or physical signature.</li>
                </ol>
                <p>boomrng may request additional information before removing any infringing material. boomrng may provide the alleged infringing party with your e-mail address so that that person can respond to your allegations.</p>
                <p>Pursuant to Title 17, United State code, Section 512(c)(2), notifications of claimed copyright infringement should be sent to Service Provider’s Designated Agent listed below. ALL INQUIRES NOT RELEVANT TO THE FOLLOWING PROCEDURE WILL RECEIVE NO RESPONSE.</p>
                <p>
                    boomrng, Limited Liability Company<br/>
                    Attn: Legal Department<br/>
                    108 BEE BRANCH BLVD<br/>
                    SIGNAL MOUNTAIN, TN 37377<br/>
                </p>
                <h3>LINKS, FRAMES AND METATAGS</h3>
                <p>You may not frame the content of our Applications unless you first obtain our express prior written consent in each case. You may not use metatags or any other "hidden text" that incorporates boomrng Trademarks or marks confusingly similar to our boomrng Trademarks without our prior written consent.</p>
                <h3>LINKS TO THIRD-PARTY WEB SITES</h3>
                <p>Our Applications may contain links to web sites controlled by third parties ("Third-Party Sites"). We are not responsible for Third-Party Sites or their content, activities, or privacy practices. Any information you share or actions you take on Third-Party Sites are governed by those sites’ terms of use and privacy statements, which you should review carefully to learn about their practices. Including links on our Applications does not imply our endorsement of Third-Party Sites, their content, or any associated organization or activity. We make no representation or warranty whatsoever about the nature of Third-Party Sites.</p>
                <h3>PURCHASE & PAYMENT TERMS</h3>
                <p>boomrng accepts major U.S. credit cards (Visa, MasterCard, American Express, and Discover). Billing occurs at the time of or shortly after your transaction. You agree that you will only use your own credit card or have express permission to use another person’s credit card.</p>
                <p>You agree that you will pay for all products you purchase and that boomrng may charge your credit card for any products purchased and for any additional amounts (including any taxes and late fees, as applicable). You are responsible for the timely payment of all fees to boomrng.</p>
                <p>You can cancel your order anytime up until 11:59 pm the day you place your order. To cancel an order email info@boomrng.us with your order number and “cancel” in the subject line. Otherwise, unless otherwise posted, all sales on boomrng are final. There are no returns or refunds.</p>
                <p>Your total price will include the price of the product(s) plus any applicable sales tax; such sales tax is based on the bill-to address and the sales tax rate in effect at the time you purchase the product(s).  All prices posted on the Applications are subject to change without notice. The price charged for a product or service will be the price in effect at the time the order is placed and will be set out in your order confirmation email. Price increases will only apply to orders placed after such changes. Posted prices do not include taxes or charges for shipping and handling. All such taxes and charges will be added to your merchandise total and will be itemized in your shopping cart and in your order confirmation email. We are not responsible for pricing, typographical, or other errors in any offer by us and we reserve the right to cancel any orders arising from such errors.</p>
                <p>Terms of payment are within our sole discretion and, unless otherwise agreed by us at the time of purchase, payment must be received by us before our acceptance of an order. You represent and warrant that (i) the credit card information you supply to us is true, correct, and complete, (ii) you are duly authorized to use such credit card for the purchase, (iii) charges incurred by you will be honored by your credit card company, and (iv) you will pay charges incurred by you at the posted prices, including all applicable taxes, if any.  Certain services boomrng provides may be paid, auto-renewing subscription services. In such event, you will be charged the stated subscription amount for the subscription period upon completion of your registration and submission of your payment information unless your membership includes a free trial period.  If you accepted an offer with a free trial for access to the Applications, your membership begins when you have completed the free trial sign-up process (i.e., when we collect your personal and payment information). At the end of your free trial, you will begin to be billed automatically each month (about every 30 days) until you cancel. Once we begin to bill you, cancellations take effect starting at the end of your current billing period, meaning there are no partial month refunds or credits. If you cancel your free trial membership at any time during the free trial period, you will not be charged.</p>
                <p>You agree that upon expiration of the initial subscription or free trial period, your subscription will automatically renew for successive periods. You agree to automatic (recurring) billing and agree to pay the charges made to your Account in connection therewith. You will be billed at the then-current applicable subscription price plus any applicable taxes. We will process payment for any renewal subscriptions using the same billing cycle as your current subscription. Subscription fees may change at any time, to the fullest extent permitted under applicable law. Your subscription, and monthly billing of your Account, will continue indefinitely until cancelled by you. If you provide a payment method and our charge results in an overdraft, chargeback or other fee from your bank, you alone are responsible for that fee. EVEN IF YOU DO NOT USE A SUBSCRIPTION OR ACCESS THE BOOMRNG SERVICES, YOU WILL BE RESPONSIBLE FOR ANY SUBSCRIPTION FEES UNTIL YOU CANCEL YOUR SUBSCRIPTION OR IT IS OTHERWISE TERMINATED.</p>
                <h3>PRODUCT FULFILLMENT</h3>
                <p>Purchased product(s) are generally shipped in 1-2 business days but may from time to time take longer. Items shipped directly to recipients with first class stamps will arrive in approximately 3 to 5 business days from the date of order. Bulk products shipped directly to customers (box of cards) will arrive in approximately 1 to 5 business days, depending on the method of shipping chosen (overnight vs. standard).  Title and risk of loss pass to you upon our transfer of the products to the carrier/delivery. Shipping and delivery dates are estimates only and cannot be guaranteed. We are not liable for any delays in shipments.</p>
                <h3>DISCLAIMERS</h3>
                <p>OUR APPLICATIONS AND THE PRODUCTS AND SERVICES AVAILABLE THROUGH THEM ARE AVAILABLE "AS IS" AND "AS AVAILABLE." TO THE FULLEST EXTENT PERMITTED BY LAW, BOOMRNG, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE PRODUCTS, SERVICES, AND THE APPLICATIONS AND YOUR USE THEREOF. BOOMRNG MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE APPLICATION OR THE BOOMRNG CONTENT OR THE CONTENT OF ANY SITES LINKED TO THE BOOMRNG APPLICATIONS, AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (1) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (2) PERSONAL INJURY OR DEATH OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE APPLICATIONS OR FROM THE CONDUCT OF ANY USERS THEREOF, (3) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (4) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM THE APPLICATIONS, (5) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE APPLICATIONS, AND (6) FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT MADE AVAILABLE VIA THE APPLICATIONS.</p>
                <p>WE EXPRESSLY DISCLAIM ANY AND ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, QUIET ENJOYMENT AND ANY OTHER WARRANTY THAT MIGHT ARISE UNDER ANY LAW. WITHOUT LIMITING THE FOREGOING, BOOMRNG MAKES NO REPRESENTATIONS OR WARRANTIES: THAT THE APPLICATIONS, PRODUCTS OR SERVICES ARE SUITABLE FOR YOU; REGARDING THE ADEQUACY OR SAFETY THEREOF FOR ANY PARTICULAR USER; THAT THE PRODUCTS OR SERVICES BOOMRNG PROVIDES WILL MEET YOUR PERSONAL NEEDS; THAT THE PRODUCTS OR SERVICES WILL BE PERMITTED IN YOUR JURISDICTION; THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR-FREE; CONCERNING ANY CONTENT SUBMITTED BY ANY USER; CONCERNING ANY THIRD PARTY'S USE OF CONTENT THAT YOU SUBMIT; THAT BOOMRNG WILL CONTINUE TO SUPPORT ANY PARTICULAR FEATURE OF ANY SERVICES; OR CONCERNING SITES AND RESOURCES OUTSIDE OF THE APPLICATIONS, EVEN IF LINKED TO/FROM THE APPLICATIONS. BOOMRNG RESERVES THE RIGHT TO MODIFY THE APPLICATIONS. BOOMRNG SHALL NOT BE RESPONSIBLE FOR PROVIDING ACCESS (E.G., COMPUTER, MOBILE DEVICE, INTERNET CONNECTION, ETC.) TO THE APPLICATIONS. BOOMRNG HAS NO OBLIGATION TO SCREEN OR MONITOR ANY CONTENT AND DOES NOT GUARANTEE THAT ANY CONTENT MADE AVAILABLE ON THE APPLICATIONS COMPLIES WITH THESE TERMS OR IS SUITABLE FOR ALL USERS. BOOMRNG SHALL NOT BE RESPONSIBLE FOR LOSS OR CORRUPTION OF DATA, AND YOU HEREBY WAIVE ALL CLAIMS WITH RESPECT TO DAMAGE TO YOUR COMPUTER SYSTEM, INTERNET ACCESS, DOWNLOAD OR DISPLAY DEVICE. TO THE EXTENT THAT A SECONDARY PARTY MAY HAVE ACCESS TO OR VIEW BOOMRNG CONTENT ON YOUR COMPUTER OR MOBILE DEVICE, YOU ARE SOLELY RESPONSIBLE FOR INFORMING SUCH PARTY OF ALL PROVISIONS, TERMS, DISCLAIMERS AND WARNINGS IN THESE TERMS. TO THE EXTENT ANY DISCLAIMER OR LIMITATION OF LIABILITY IN THESE TERMS DOES NOT APPLY, ALL APPLICABLE EXPRESS, IMPLIED, AND STATUTORY WARRANTIES WILL BE LIMITED IN DURATION TO A PERIOD OF THIRTY (30) DAYS AFTER THE DATE ON WHICH YOU FIRST USED THE APPLICATIONS, AND NO WARRANTIES SHALL APPLY AFTER SUCH PERIOD.  WE RESERVE THE RIGHT TO CORRECT ANY ERRORS IN OUR APPLICATIONS OR SERVICES. YOU ARE SOLELY RESPONSIBLE FOR MAKING BACKUP COPIES OF AND PRESERVING ALL INFORMATION IN YOUR ADDRESS BOOK. IF YOU RELY ON INFORMATION CONTAINED IN OR ON OUR APPLICATIONS OR SERVICES, YOU DO SO ENTIRELY AT YOUR OWN RISK.</p>
                <h3>LIMITATION OF LIABILITY</h3>
                <p>UNDER NO CIRCUMSTANCES WILL BOOMRNG (OR ITS MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES, SERVICE PROVIDERS, REPRESENTATIVES AND AGENTS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR USE OF OUR APPLICATIONS, INCLUDING ANY (1) ERRORS, OMISSIONS, INTERRUPTIONS, OR INACCURACIES IN OUR APPLICATIONS OR ANY SERVICES, (2) FAILURE TO STORE OR PRESERVE INFORMATION IN CONNECTION WITH YOUR ADDRESS BOOK, OR (3) DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES (INCLUDING LOST REVENUES OR PROFITS, LOSS OF BUSINESS, OR LOSS OF DATA) ARISING OUT OF YOUR USE OR MISUSE OF OUR APPLICATIONS, REGARDLESS OF THE THEORY OF LIABILITY, WHETHER TORT (INCLUDING NEGLIGENCE), CONTRACT, OR ANY OTHER LEGAL OR EQUITABLE THEORY AND EVEN IF WE ARE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LOSS. SOME STATES DO NOT ALLOW THE LIMITATION OF LIABILITY FOR THESE KINDS OF DAMAGES, SO THESE LIMITATIONS OR EXCLUSIONS MAY NOT APPLY TO YOU. YOU RELEASE BOOMRNG (AND ITS MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES, SERVICE PROVIDERS, REPRESENTATIVES AND AGENTS) FROM ANY CLAIM RELATING TO YOUR USE OF OUR APPLICATIONS OR SERVICES. YOU AGREE THAT THE LIABILITY OF BOOMRNG (AND ITS MEMBERS, DIRECTORS, OFFICERS, EMPLOYEES, SERVICE PROVIDERS, REPRESENTATIVES, AND AGENTS), IF ANY, ARISING OUT OF ANY LEGAL CLAIM ARISING FROM YOUR USE OF OUR APPLICATIONS WILL NOT EXCEED THE ACTUAL AMOUNT PAID BY YOU FOR THE DEFECTIVE PRODUCT OR SERVICE THAT YOU HAVE PURCHASED.</p>
                <p>YOU ARE RESPONSIBLE FOR MAINTAINING THE SECURITY OF YOUR ACCOUNT AND PASSWORD. BOOMRNG WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE FROM YOUR FAILURE TO MAINTAIN THE SECURITY OF YOUR ACCOUNT OR PASSWORD. YOU ARE RESPONSIBLE FOR ALL ACTIVITY THAT OCCURS UNDER YOUR ACCOUNT, INCLUDING ALL PURCHASES.</p>
                <h3>INDEMNIFICATION</h3>
                <p>You agree to indemnify and hold harmless boomrng (and its members, directors, officers, employees, service providers, representatives, and agents) from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from (i) your use of and/or access to the Applications or boomrng products and services, (ii) any use of your Account by anyone other than you, and (iii) your violation of these Terms or any other terms, instructions, directions or agreements concerning or relating to the Applications, by you or by anyone under your control.  This defense and indemnification obligation will survive these Terms and your use of the Applications. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter for which we are entitled to indemnification. You agree to provide us with whatever cooperation we reasonably request.</p>
                <h3>CHANGES TO THESE TERMS</h3>
                <p>boomrng reserves the right to change any of these Terms, or any policy or guideline of the Applications, at any time and in its sole discretion. When we make changes, we will revise the "last updated" date at the top of the Terms. Any changes will be effective immediately upon posting on the Applications. Your continued use of the Applications following the posting of changes will constitute your acceptance of such changes. We encourage you to review these Terms whenever you visit one of our Applications.</p>
                <h3>ARBITRATION AGREEMENT; CLASS WAIVER; JURY WAIVER</h3>
                <p>YOU AND BOOMRNG ARE AGREEING TO GIVE UP ANY RIGHTS TO LITIGATE CLAIMS IN A COURT OR BEFORE A JURY, OR TO PARTICIPATE IN A CLASS ACTION OR REPRESENTATIVE ACTION WITH RESPECT TO A CLAIM. OTHER RIGHTS THAT YOU WOULD HAVE IF YOU WENT TO COURT MAY ALSO BE UNAVAILABLE OR MAY BE LIMITED IN ARBITRATION.  ANY CLAIM, DISPUTE OR CONTROVERSY (WHETHER IN CONTRACT, TORT OR OTHERWISE, WHETHER PRE-EXISTING, PRESENT OR FUTURE, AND INCLUDING STATUTORY, CONSUMER PROTECTION, COMMON LAW, INTENTIONAL TORT, INJUNCTIVE AND EQUITABLE CLAIMS) BETWEEN YOU AND US ARISING FROM OR RELATING IN ANY WAY TO YOUR PURCHASE OR USE OF BOOMRNG PRODUCTS OR SERVICES, WILL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION.</p>
                <p>The arbitration will be administered by the American Arbitration Association ("AAA") in accordance with the Consumer Arbitration Rules (the "AAA Rules") then in effect, except as modified by this Section. (The AAA Rules are available at adr.org or by calling the AAA at 1-800-778-7879.) The Federal Arbitration Act will govern the interpretation and enforcement of this Section.  The arbitrator will have exclusive authority to resolve any dispute relating to arbitrability and/or enforceability of this arbitration provision, including any unconscionability challenge or any other challenge that the arbitration provision or the Agreement is void, voidable or otherwise invalid. The arbitrator will be empowered to grant whatever relief would be available in court under law or in equity. Any award of the arbitrator(s) will be final and binding on each of the parties and may be entered as a judgment in any court of competent jurisdiction.</p>
                <p>You agree to an arbitration on an individual basis. In any dispute, NEITHER YOU NOR BOOMRNG WILL BE ENTITLED TO JOIN OR CONSOLIDATE CLAIMS BY OR AGAINST OTHER CUSTOMERS IN COURT OR IN ARBITRATION OR OTHERWISE PARTICIPATE IN ANY CLAIM AS A CLASS REPRESENTATIVE, CLASS MEMBER OR IN A PRIVATE ATTORNEY GENERAL CAPACITY. The arbitral tribunal may not consolidate more than one person's claims, and may not otherwise preside over any form of a representative or class proceeding. The arbitral tribunal has no power to consider the enforceability of this class arbitration waiver and any challenge to the class arbitration waiver may only be raised in a court of competent jurisdiction.  If any provision of this arbitration agreement is found unenforceable, the unenforceable provision will be severed and the remaining arbitration terms will be enforced.</p>
                <p>If you reside in the European Union, you can find information about online dispute resolution here:<a href="https://webgate.ec.europa.eu/odr/main/index.cfm?event=main.home.show&lng=EN" target="_blank"> https://webgate.ec.europa.eu/odr/main/index.cfm?event=main.home.show&lng=EN</a>. Please note that we reserve the right not to participate in forms of alternative dispute resolution.
                </p>
                <h3>GENERAL</h3>
                <p>These Terms, which include the <span className="link" onClick={()=> history.push('/privacy-and-security')}>Privacy Policy</span>, are the complete agreement between you and boomrng regarding your use of our Applications and, to the extent the parties are permitted under these Terms to initiate litigation in court, are governed by the laws of the State of Tennessee applicable to agreements made and completely performed in the State. You irrevocably agree to bring any claim or dispute relating to your use of our Applications or these Terms exclusively in the state and federal courts located in the State and County of Hamilton County, Tennessee, to submit to the exclusive jurisdiction of those courts, and to waive any jurisdictional, venue, inconvenient forum, or other objections to those courts. YOU AND BOOMRNG AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE APPLICATIONS MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED TO THE EXTENT PERMITTED BY LAW.  If a court of competent jurisdiction determines that any provision of these Terms is unenforceable for any reason, then that provision will be deleted and the remaining provisions will be enforceable to the fullest extent permitted by law. In the event a court having jurisdiction over the parties holds any provision of this Agreement invalid or unenforceable, the parties shall negotiate in good faith to replace the invalid or unenforceable provision, if possible, with a valid provision that most closely approximates the intent and economic effect of the invalid provision. You agree that we may provide you with notices by posting on our Applications, by email, or by regular mail. If we do not exercise or enforce a right or remedy in these Terms or otherwise available, you agree we have nor waived such right or remedy. The term "including" in these Terms means "including, but not limited to."</p>
                <p>You will not assign any of your rights or delegate any of your obligations under these Terms without our prior written consent. Any purported assignment or delegation in violation of this Section is null and void. No assignment or delegation relieves you of any of your obligations under these Terms.  We may assign our rights, obligations and/or these Terms at any time in our sole discretion without notice to you.</p>
                <p>The failure by us to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any right or provision will be effective only if in writing and signed by a duly authorized representative of boomrng, Limited Liability Company.</p>
                <p>These Terms do not and are not intended to confer any rights or remedies upon any person other than you.</p>
                <p>We will not be liable or responsible to you, nor be deemed to have defaulted or breached these Terms, for any failure or delay in our performance under these Terms when and to the extent such failure or delay is caused by or results from acts or circumstances beyond our reasonable control, including, without limitation, acts of God, epidemic, pandemic, flood, fire, earthquake, explosion, governmental actions, war, invasion or hostilities (whether war is declared or not), terrorist threats or acts, riot or other civil unrest, national emergency, revolution, insurrection, epidemic, lockouts, strikes or other labor disputes (whether or not relating to our workforce), or restraints or delays affecting carriers or inability or delay in obtaining supplies of adequate or suitable materials, materials or telecommunication or internet breakdown or power outage.</p>
                <h3>NOTICES</h3>
                <p>To You: We may provide any notice to you under these Terms by: (i) sending a message to the email address you provide or (ii) by posting to the Applications. Notices sent by email will be effective when we send the email and notices we provide by posting will be effective upon posting. It is your responsibility to keep your email address current.</p>
                <p>To Us: To give us notice under these Terms, you must contact us by personal delivery, overnight courier or registered or certified mail to boomrng, Limited Liability Company, P.O. Box 698, Signal Mountain, TN 37377. We may update the address for notices to us by posting a notice on the Applications. Notices provided by personal delivery will be effective immediately. Notices provided by facsimile transmission or overnight courier will be effective one business day after they are sent. Notices provided by registered or certified mail will be effective three business days after they are sent.</p>
                <h3>QUESTIONS</h3>
                <p>For any questions or comments you may have about these Terms, please contact us at: info@boomrng.us</p>
            </div>
        </div>
    )
}

export default Terms
